### ISSUE TITLE
Config to make Scrapmire sound not global

### ISSUE THREAD

**Issue by brandyyn** [lincolnrelias/Scrapmire#1] opened 2024-01-18 01:38 UTC
some of my friends hate that its a global sound, i dont mind personally but it would be cool for it to be a config option since i love scrapmire

**Comment by aaronhowser1** [comment] 2024-01-18 22:09
I am begging you

**Comment by brandyyn** [comment] 2024-01-18 22:09
add more voice lines
like giggity giggity goo

**Comment by brandyyn** [comment] 2024-01-18 22:10
@lincolnrelias

**Comment by lincolnrelias** [comment] 2024-01-18 23:33
it wasn't intended to play globally, pretty sure it's fixed now, lmk if still happening

**Comment by brandyyn** [comment] 2024-01-18 23:34
if u dont add more voice lines i will personally fuck you

**Comment by lincolnrelias** [comment] 2024-01-19 00:17
I'm trying bro relax 😭

**Comment by brandyyn** [comment] 2024-01-19 00:18
> I'm trying bro relax 😭

hahahah love u bro

**Comment by aaronhowser1** [comment] 2024-01-19 00:20
Make a new issue for it smfh brandyn i will actually stab you

**Comment by brandyyn** [comment] 2024-01-19 00:20
> Make a new issue for it smfh brandyn i will actually stab you

I will fuck your fat ass

**Comment by aaronhowser1** [comment] 2024-01-19 00:23
Why do you choose to be the way that you are

**Comment by brandyyn** [comment] 2024-01-19 00:24
> Why do you choose to be the way that you are

If I made a new issue it would DOUBLE the amount of issues he has ever had

**Comment by aaronhowser1** [comment] 2024-01-19 00:31
Theoretically, maybe, possibly

what if it constantly went giggity while held, like the toy robot

**Comment by brandyyn** [comment] 2024-01-19 00:31
> Theoretically, maybe, possibly
> 
> what if it constantly went giggity while held, like the toy robot

THATS A GOOD IDEA ESPECIALLY SINCE ITS WORTH SOOO MUCH

**Comment by lincolnrelias** [comment] 2024-01-19 18:41
added a bunch of voicelines as sfx, I'm testing the suggestions of playing sounds while you carry it but that'll take a little more time

**Comment by aaronhowser1** [comment] 2024-01-19 18:43
Dev confirmed to be goated with the sauce bustin it down sexual style

**Comment by brandyyn** [comment] 2024-01-19 18:54
> added a bunch of voicelines as sfx, I'm testing the suggestions of playing sounds while you carry it but that'll take a little more time

MY GOAT

**Comment by brandyyn** [comment] 2024-01-19 21:02
It is still a global sound :/

**Comment by lincolnrelias** [comment] 2024-01-19 22:56
> It is still a global sound :/

is it only on pickup or on drop too?

**Comment by brandyyn** [comment] 2024-01-20 03:19
> > It is still a global sound :/
> 
> is it only on pickup or on drop too?

i think both?

**Comment by lincolnrelias** [comment] 2024-01-20 19:46
> It is still a global sound :/

all right now I'm pretty sure it's fixed, even tested it with a friend so should be ok, but if it has any other problems lmk

**Closed as completed** 2024-01-20 19:46 UTC
